### ISSUE TITLE
Transfer Project Ownership to Unkso Organization

### ISSUE THREAD

**Issue by ELD** [unkso/Unknown-Soldiers-Engineering#1]
A long time ago, I created an Unkso organization and added everyone to it. I think we should transfer ownership of this repository to that organization and properly license it so no one can reuse the resources without our express permission.

It doesn't matter much if the project is public or private and having it under an organization abstracts away ownership from one person.

[Unkso Organization](https://github.com/unkso)

**Comment by Padarom** [comment]
UnkSo is now the owner.
